### ISSUE TITLE
Uncaught Error: Invalid arguments

### ISSUE THREAD

**Issue by evanweible-wf** [maxwellpeterson-wf/GridHub#30]
No idea why this happens, but it happens sometimes:

```
Uncaught Uncaught Error: Invalid arguments(s)
Stack Trace:
Invalid arguments(s)
    at dart.b (http://gridhub.club/build/web/gridhub.dart.js:1716:3)
    at dart.Yx (http://gridhub.club/build/web/gridhub.dart.js:1712:47)
    at VR.ej (http://gridhub.club/build/web/gridhub.dart.js:2393:37)
    at dart.iP.static.Gl (http://gridhub.club/build/web/gridhub.dart.js:5402:318)
    at Ba.$1 (http://gridhub.club/build/web/gridhub.dart.js:638:10)
    at Q.aN (http://gridhub.club/build/web/gridhub.dart.js:745:20)
    at dart.J.kH (http://gridhub.club/build/web/gridhub.dart.js:8497:35)
    at yz.Ww (http://gridhub.club/build/web/gridhub.dart.js:622:3)
    at PB.$0 (http://gridhub.club/build/web/gridhub.dart.js:8106:84)
    at R8.Gr (http://gridhub.club/build/web/gridhub.dart.js:4009:41)
    at HEa.$1 (http://gridhub.club/build/web/gridhub.dart.js:8102:32)
```

**Comment by maxwellpeterson-wf** [comment]
I _think_ this is fixed
